version: "3.9"

services: 
  frontend: 
    build: .
    ports:
      - "3000:8080"
    depends_on:
      - api

  api:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./src/db:/app/src/db
    command: sh -c "npm install -g json-server && json-server --watch ./src/db/db.json --port 3000"    
